#pragma once

// ARK (309.53) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARK_DinoBlueprintBase_RootBoneName_Ramming_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_Ramming_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3810
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3810_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4667
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4667_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_726
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_726_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3809
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3809_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3808
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3808_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3807
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3807_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3806
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3806_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4666
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4666_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4665
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4665_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3805
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3805_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3804
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3804_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4662
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4662_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_RotationOffsetBlendSpace_228
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_RotationOffsetBlendSpace_228_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4661
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4661_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3803
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3803_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3802
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3802_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4660
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4660_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4659
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4659_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3801
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3801_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3800
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3800_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3799
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3799_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_725
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_725_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3798
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3798_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3797
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3797_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3796
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3796_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_240
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_240_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_239
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_239_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ApplyAdditive_312
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ApplyAdditive_312_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3795
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3795_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3794
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3794_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4654
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4654_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3793
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3793_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3792
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3792_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3791
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3791_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4653
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4653_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4652
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4652_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_Ramming_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming
struct UDinoBlueprintBase_RootBoneName_Ramming_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
