#pragma once

// ARK (309.53) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARK_DinoBlueprintBase_RootTransformIK_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootTransformIK_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3924
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3924_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ModifyBone_750
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ModifyBone_750_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3923
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3923_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_RotationOffsetBlendSpace_252
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_RotationOffsetBlendSpace_252_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3922
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3922_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3921
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3921_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4774
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4774_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3920
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3920_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3919
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3919_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4773
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4773_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4772
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4772_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3918
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3918_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4771
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4771_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3917
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3917_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3916
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3916_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4769
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4769_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3915
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3915_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3914
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3914_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4768
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4768_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4767
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4767_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3913
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3913_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3912
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3912_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4766
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4766_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4765
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4765_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4764
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4764_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendSpacePlayer_192
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendSpacePlayer_192_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3910
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3910_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3909
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3909_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ApplyAdditive_324
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ApplyAdditive_324_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootTransformIK_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.ExecuteUbergraph_DinoBlueprintBase_RootTransformIK
struct UDinoBlueprintBase_RootTransformIK_C_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
